"""add auth method to authorization codes

Revision ID: 16e6fa05bf9d
Revises: d577c80af4d0
Create Date: 2026-08-12 08:16:40.691493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e6fa05bf9d'
down_revision: Union[str, None] = 'd577c80af4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'authorization_codes',
        sa.Column(
            'auth_method',
            sa.String(length=20),
            server_default=sa.text("'password'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authorization_codes', 'auth_method')
    # ### end Alembic commands ###
