"""add logout uri to oauth clients

Revision ID: 87b77b1722e9
Revises: 16e6fa05bf9d
Create Date: 2026-08-12 08:44:38.160889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87b77b1722e9'
down_revision: Union[str, None] = '16e6fa05bf9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_clients', sa.Column('logout_uri', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_clients', 'logout_uri')
    # ### end Alembic commands ###
