"""add client user blocks and home url

Revision ID: 8d469400ede9
Revises: 3df649313266
Create Date: 2026-08-12 07:56:50.620490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d469400ede9'
down_revision: Union[str, None] = '3df649313266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_user_blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_user_blocks_client_id'), 'client_user_blocks', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_user_blocks_email'), 'client_user_blocks', ['email'], unique=False)
    op.create_index(op.f('ix_client_user_blocks_user_id'), 'client_user_blocks', ['user_id'], unique=False)
    op.add_column('oauth_clients', sa.Column('home_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_clients', 'home_url')
    op.drop_index(op.f('ix_client_user_blocks_user_id'), table_name='client_user_blocks')
    op.drop_index(op.f('ix_client_user_blocks_email'), table_name='client_user_blocks')
    op.drop_index(op.f('ix_client_user_blocks_client_id'), table_name='client_user_blocks')
    op.drop_table('client_user_blocks')
    # ### end Alembic commands ###
